[package]
name = "schema-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
schema-bridge-core = { path = "../schema-bridge-core" }
schema-bridge-macro = { path = "../schema-bridge-macro" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
